[package]
name = "fibonacci"
version = "0.1.0"
edition = "2021"
default-run = "fibonacci"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ziskos = { path = "../../ziskos/entrypoint" }
