[package]
name = "template-host"
version = "0.1.0"
edition = "2024"

[dependencies]
zisk-sdk = { git = "https://github.com/0xPolygonHermez/zisk.git", tag = "v1.0.0-beta" }             
template-common = { path = "../common" }
anyhow = "1.0"

# Only needed if you want to make async calls to the prover client (e.g. streaming or a remote prover).
# tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[build-dependencies]
zisk-sdk = { git = "https://github.com/0xPolygonHermez/zisk.git", tag = "v1.0.0-beta" }
